// Generated by https://quicktype.io

export interface PolizaRecive {
  success: boolean;
  poliza:  Poliza;
}

export interface Poliza {
  fechaVencimiento: string;
  numeroPoliza:     string;
  lineaCaptura:     string;
  total:            number;
}
