// Generated by https://quicktype.io

export interface CalculoConcepto {
  data:    Data;
  success: boolean;
  mensaje?:string;
}

export interface Data {
  total:        number;
  conceptos:    Concepto[];
  lineaDetalle: string;
}

export interface Concepto {
  id:              number;
  clave:           string;
  cantidad:        number;
  descripcion:     string;
  ejercicioFiscal: number;
  importe:         number;
  importeUnitario?:number;
  unitario?:       number;
  conceptoArea?:   number;

}
