// Generated by https://quicktype.io

export interface TopLevel {
  data:    Data;
  success: boolean;
  mensaje?: string;
}

export interface Data {
  total:         number;
  conceptos:     Concepto[];
  contribuyente: Contribuyente;
  domicilio:     Domicilio;
  lineaDetalle:  string;
}

export interface Concepto {
  id:              number;
  clave:           string;
  cantidad:        number;
  descripcion:     string;
  ejercicioFiscal: number;
  importe:         number;
  padre?:          number;
  no_hojas?:       number;
}

export interface Contribuyente {
  nombre:          string;
  tipoPersona:     string;
  razonSocial?:     string;
  primerApellido:  string;
  segundoApellido: string;
  rfc:             string;
  curp:            string;
  id:              number;
}

export interface Domicilio {
  calle:          string;
  numeroExterior: string;
  numeroInterior: string;
  colonia:        string;
  municipio:      string;
  estado:         string;
  origen?:         string;
  codigoPostal:   string;
  tipoDomicilio?:  string;
  referencia?:     string;
  id:             number;
}
