// Generated by https://quicktype.io

export interface TopLevel {
  data:    Data;
  success: boolean;
  mensaje?: string;
}

export interface Data {
  total:         number;
  conceptos:     Concepto[];
  contribuyente: Contribuyente;
  domicilio:     Domicilio;
  lineaDetalle:  string;
  adicional?:    Adicionales;
  observaciones?:string;
}

export interface Adicionales {
  capacidadPasajeros:   string;
  combustible:          string;
  vMarca:               string;
  vSubmarca:            string;
  centimetrosCubicos:   string;
  motor:                string;
  noCilindros:          string;
  noSerie:              string;
  servicio:             string;
  tonelaje:             string;
  placaAnterior:        string;
  placa:                string;
  idVehiculo:           string;
  estadoVehiculo:       string;
  modelo:               string;
  valorFactura:         string;
  tipoVehiculo:         string;
  fechaFactura:         string;
  valorVenta:           string;
  procedencia:          string;
  clase:                string;
}

export interface Concepto {
  id:              number;
  clave:           string;
  cantidad:        number;
  descripcion:     string;
  ejercicioFiscal: number;
  importe:         number;
  importeUnitario?:number;
  padre?:          number;
  no_hojas?:       number;
  unitario?:       number;
  conceptoArea?:    number;
}

export interface Contribuyente {
  nombre:          string;
  tipoPersona:     string;
  razonSocial?:     string;
  primerApellido:  string;
  segundoApellido: string;
  rfc:             string;
  curp:            string;
  id:              number;
}

export interface Domicilio {
  calle:          string;
  numeroExterior: string;
  numeroInterior: string;
  colonia:        string;
  municipio:      string;
  estado:         string;
  origen?:         string;
  codigoPostal:   string;
  tipoDomicilio?:  string;
  referencia?:     string;
  id:             number;
}
