// Generated by https://quicktype.io

export interface Conceptos {
  data:    MenuConceptos[];
  success: boolean;
}

export interface MenuConceptos {
  pk:             number;
  titulo:         string;
  idConcepto:     number;
  combinable:     number;
  formulario:     number;
  rol:            number;
  tipoMovimiento: number;
  gestora:        number;
  url:            string;
  costo:          number;
}
/*export interface Conceptos {
  id:                    number;
  textoTitulo:           string;
  idConcepto:            number | string;
  consumoInterno:        null;
  url:                   string;
  textoMensaje:          string;
  muestraIndex:          string;
  urlIcono:              string;
  estatus:               number;
  nivelUso:              null;
  opcionFormulario:      number;
  opcionPagoUnicoPoliza: number;
  opcionCantidadUnica:   number;
  posicionLista:         null;
  combo:                 null;
  nivelBd:               null;
  menuHijo:              any[];
  error:                 null;
  padreId:               number;
  tipoMovimiento:        number;
  gestora:               number;
  pagoEnLinea:           null;
}*/
