// Generated by https://quicktype.io

export interface InsertarPersonaOficio {
    "soap:Envelope": SoapEnvelope;
  }
  
  export interface SoapEnvelope {
    "@attributes": SoapEnvelopeAttributes;
    "soap:Body":   SoapBody;
  }
  
  export interface SoapEnvelopeAttributes {
    "xmlns:soap": string;
  }
  
  export interface SoapBody {
    "ns2:insertaPeticionResponse": Ns2InsertaPeticionResponse;
  }
  
  export interface Ns2InsertaPeticionResponse {
    "@attributes":   Ns2ConsultaFolioPagoResponseAttributes;
    resultado: resultado;
  }
  
  export interface Ns2ConsultaFolioPagoResponseAttributes {
    "xmlns:ns2": string;
  }
  
  export interface resultado {
    "#text": string;
  }
  