// Generated by https://quicktype.io

export interface ValidateFolioPago {
    "soap:Envelope": SoapEnvelope;
  }
  
  export interface SoapEnvelope {
    "@attributes": SoapEnvelopeAttributes;
    "soap:Body":   SoapBody;
  }
  
  export interface SoapEnvelopeAttributes {
    "xmlns:soap": string;
  }
  
  export interface SoapBody {
    "ns2:consultaFolioPagoResponse": Ns2ConsultaFolioPagoResponse;
  }
  
  export interface Ns2ConsultaFolioPagoResponse {
    "@attributes":   Ns2ConsultaFolioPagoResponseAttributes;
    folioPagoResult: ValidarFolioPago;
  }
  
  export interface Ns2ConsultaFolioPagoResponseAttributes {
    "xmlns:ns2": string;
  }
  
  export interface ValidarFolioPago {
    "#text": string;
  }
  