// Generated by https://quicktype.io

export interface ValidateVehicle {
  "soap:Envelope": SoapEnvelope;
}

export interface SoapEnvelope {
  "@attributes": SoapEnvelopeAttributes;
  "soap:Body":   SoapBody;
}

export interface SoapEnvelopeAttributes {
  "xmlns:soap": string;
}

export interface SoapBody {
  "ns2:validarVehiculoResponse": Ns2ValidarVehiculoResponse;
}

export interface Ns2ValidarVehiculoResponse {
  "@attributes":   Ns2ValidarVehiculoResponseAttributes;
  validarVehiculo: ValidarVehiculo;
}

export interface Ns2ValidarVehiculoResponseAttributes {
  "xmlns:ns2": string;
}

export interface ValidarVehiculo {
  "#text": string;
}
