export enum TipoServicio {
  SMYTREFRENDO = 'T: 08',
  SMYTALTAVEHICULONUEVO = 'T: 01',
  SMYTALTAVEHICULOUSADO = 'T: 10',
  SMYTBAJA = 'T: 03',
  SMYTTARJETADUPLICADA = 'T: 05',
  SMYTSUSTITUCIONPLACA = 'T: 02'
}
